### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by danicarla** [openboleto/openboleto#114]
Oi pessoal boa tarde tudo bom?

Eu gostaria de usar somente o boleto do Banco do Brasil, então ñão queria subir pro meu servidor arquivos de outros bancos para ficar ocupando espaço... posso apagar outras pastas?

Pra mim esse tal de composer pode até facilitar a vida, mas fica muito lixo perdido pro meio

**Comment by nicolahsss** [comment]
Pode sim
