### ISSUE TITLE
Segundo desconto - Boleto Itaú

### ISSUE THREAD

**Issue by rodrigosarri** [openboleto/openboleto#119]
No boleto Itaú é possível configurar um segundo e terceiro desconto segundo a documentação do (PDF) do Itaú, porém, não encontrei essa informação nos códigos e como devo configurar. Isso foi desenvolvido?

https://download.itau.com.br/bankline/layout_cobranca_400bytes_cnab_itau_mensagem.pdf
 
### -> (16)SACADOR/AVALISTA (página 19 e 20).

Normalmente  deve  ser  preenchido  com  o  nome  do  sacador/avalista.  Alternativamente  este  campo poderá ter dois outros usos: 

a) 2º e 3º descontos: para se operar com mais de um desconto (depende de cadastramento prévio do indicador 19.0 pelo Banco Itaú, conforme Item 5), deve-se respeitar a seguinte disposição:

**Posição 352 a 353 : Brancos 
Posição 354 a 359 : Data do 2º desconto (DDMMAA)
Posição 360 a 372 : Valor do 2º desconto 
Posição 373 a 378 : Data do 3º desconto (DDMMAA)
Posição 379 a 391 : Valor do 3º desconto 
Posição 392 a 394 : Brancos**

b) Mensagens  ao  sacado:  se  utilizados  as  instruções  93  ou  94  (Nota  11),  transcrever  a  mensagem desejada.

Como eu preciso especificamente desse segundo desconto, gostaria saber se poderá ser feito (posso ajudar se for o caso, como desenvolvimento e inclusive com testes) esse desenvolvimento com o banco Itaú.

Obrigado.

**Comment by Rctnet** [comment]
Bom dia, a parte impressa do boleto não tem relação direta com a remessa, peço que poste sua issue no repositório quilhasoft/opencnabphp

**Comment by rodrigosarri** [comment]
Olá, se eu não colocar o segundo desconto no boleto (no código de barras), ele não é aceito em casas lotéricas ou no próprio banco (pagando no caixa do banco). Ou seja, não precisa ter relação direta com a remessa. 

OBS: Eu testei isso pagando o boleto e o mesmo retornou com essa informação.

**Comment by Rctnet** [comment]
Olá amigo, no código de barras do Boleto só vai um vencimento e o valor, fora outros dados não importantes agora mas que são padronizados pela febraban,

Com a ultima atualização no sistema integrado de pagamento de boletos os dados acessórios como descontos multas e afins são passados para o banco cobrador via remessa, esse mesmos dados são repassados aos sistemas de outros bancos na hora que o usuário tenta pagar o boleto na lotérica, por exemplo, 

O Boleto padrão nunca teve espaço especifico para descontos variados , sempre foram colocados no campo instruções e ficavam a cargo do atendente ler e aplicar,  com implementação do sistema integrado de cobrança não mudou nada para o boleto impresso, ficando os textos de descontos múltiplos e afins apenas para conhecimento do pagador.

Ainda falando sobre o código de barras , não houve nenhuma alteração com as novas regras do código de barras, passei por esse processo de implementação dos boletos registrados e te garanto que apenas com a linha digitável  e os dados registrados corretamente na remessa é possível pagar boletos com multas descontos e afins.

Quando a remessa não tenho certeza quanto aos descontos com datas, mas para a multa não pude passar ela pelo arquivo de remessa, tive que configurar dentro do internet banking , toda vez que tentei enviar o registro tipo 2 o sistema recusou o arquivo inteiro, falando com o pessoal do suporte do banco Itaú, me disseram que deveria deixar isso configurado no internet banking, opero com meus clientes desse modo a mais de um ano, porem nenhum deles precisa de descontos múltiplos, na verdade não sei nem se ainda é suportado, porem se abrir um issue no repositório https://github.com/QuilhaSoft/OpenCnabPHP  ficarei feliz em te ajudar para que possa alcançar seu objetivo,
Que a força esteja com você.
