### ISSUE TITLE
personalisar logo do boleto

### ISSUE THREAD

**Issue by marcelocajaiba** [openboleto/openboleto#125]
eu queria personalizar a logomarca do boleto, de modo que não alterasse funções na classe abstract. alguém tem alguma idéia?  obrigado

**Comment by fredroo** [comment]
melhor resolver só para o seu caso e deixar por ai mesmo, tipo cria uma página do pdf só para seus dados ou acima do boleto na mesma folha do pdf. cria o código separado e joga na hora de gerar o pdf ou html.
é melhor até para quem vai pagar o boleto.

**Comment by marcelocajaiba** [comment]
obrigado meu caro, eu fiz isso agora  : 
       foreach ($this->boletos as $item) {
            if ($item->logo_banco) {
                $item->logo_banco = 'logo.jpg';
            }
        }
