### ISSUE TITLE
Impressão de carne do sicoob

### ISSUE THREAD

**Issue by marcoprodata** [openboleto/openboleto#131]
Mestres,
Criei o objeto assim:
$boleto = new Sicoob(
   array(..., 'layout' => 'default-carne-sicoob.phtml'),
   array(..., 'layout' => 'default-carne-sicoob.phtml'),
   array(..., 'layout' => 'default-carne-sicoob.phtml')
);

return $boleto->getOutput();

Mas ele só exibe um boleto no carne, apenas o primeiro, como fazer para a saída ser todos os boletos?

**Comment by Rctnet** [comment]
Bom dia, talvez não seja isso o que está procurando, mas foi adicionado suporte para a biblioteca Quilhasoft\jasperPHP que gera o boleto em PDF ( SEM JAVA ) e tem um exemplo de carne em https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/blob/master/itauJasper.php

**Comment by marcoprodata** [comment]
> Bom dia, talvez não seja isso o que está procurando, mas foi adicionado suporte para a biblioteca Quilhasoft\jasperPHP que gera o boleto em PDF ( SEM JAVA ) e tem um exemplo de carne em https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/blob/master/itauJasper.php

Vou testar com a opção do Jasper, eu gostei mundo da versão html, já me atendia o layout, a única coisa q precisava nele é q gerasse de vários, mas vou testar essa opção do jasper.

**Comment by websignsistemas** [comment]
olá @marcoprodata você conseguiu achar uma solução?

**Comment by marcoprodata** [comment]
> olá @marcoprodata você conseguiu achar uma solução?

Não, acabei usando a impressão com o arquivo jasper mesmo, pra mim no fim foi melhor pq já temos aqui na empresa conhecimento do jasper e ai até personalizamos um pouco o report
