### ISSUE TITLE
Número do convênio

### ISSUE THREAD

**Issue by pkhadson** [openboleto/openboleto#134]
Pessoal, já revirei o Google e não consigo descobrir o que é esse número do convênio. Também queria sabe se posso gerar um boleto para a minha conta pessoal do Bradesco

**Comment by Rctnet** [comment]
Boa tarde @pkhadson, o numero do convenio é fornecido pelo gerente da conta no ato da contratação do cobrança de boleto, esse serviço só pode ser usado por pessoa jurídica, porem alguns sites como pagseguro fazem a cobrança para você usado o cnpj deles.
