### ISSUE TITLE
Santander - Desconto duplo (pagt em diferentes datas)

### ISSUE THREAD

**Issue by rodrigosarri** [openboleto/openboleto#135]
No boleto Santander, existe a possibilidade de agendar descontos mediante data de pagamento?
Exemplo:

Pagar na data 01/XX/XXXX - Desconto de R$ XX,XX
Pagar na data 05/XX/XXXX - Desconto de R$ XX,XX

Se existir a possibilidade, é possível transformar em uma feature para desenvolvimento?

Obrigado.

**Comment by Rctnet** [comment]
Ola, em qualquer boleto esse você pode incluir esses textos nas mensagens, porem o banco tem que suportar pelo arquivo de remessa, se não fica sem efeito se o usuário for pagar o boleto por meios eletrônicos, o banco Santander suporta essas opções e na minha biblioteca quilhasoft\opencnabphp também é suportado

**Comment by rodrigosarri** [comment]
Bom dia! Obrigado pela resposta. Não precisa estar disponível no boleto a informação? Somente no cnab?

**Comment by Rctnet** [comment]
Bom dia, no boleto é só informativo, e é sempre bom colocar mas se não colocar no cnab, não tem efeito

**Comment by rodrigosarri** [comment]
Entendi, obrigado. Acho que precisa apenas então atualizar o readme de como adicionar dois descontos no cnab.
