### ISSUE TITLE
Bradesco - DS

### ISSUE THREAD

**Issue by marcellribeiro** [openboleto/openboleto#138]
Boa tarde. Não consigo fazer o boleto ficar DS pro Bradesco, sempre fica como DM - Duplicata Mercantil.

Na Remessa que enviei marquei como DS. Isso tem algum problema? Por que não to conseguindo pagar o boleto, o meu banco diz que o boleto não está registrado.

**Comment by fredroo** [comment]
@marcellribeiro tenta uma ajuda com o bradesco da sua cidade, liga para o pessoal de TI do Banco na sua cidade, o outro administrador entende mais que eu e pode ser que te ajude mais tarde ou amanhã quando ele ver e tiver tempo.

**Comment by fredroo** [comment]
@marcellribeiro da uma lida na página inicial e olha os outros projetos cnab

**Comment by marcellribeiro** [comment]
@fredroo obrigado pela resposta rápida, amigo. 

Já fucei muita coisa, troquei para todas as carteiras disponíveis e nada do boleto virar DS. Até mudei o código pra permitir a carteira 02, mas mesmo assim não funcionou.

Seguem 2 anexos, pra tentar elucidar melhor. 

_No primeiro é do sistema legado e o boleto funciona normalmente (DS)._ 
<img width="758" alt="Screen Shot 2020-06-24 at 16 33 02" src="https://user-images.githubusercontent.com/7966620/85619279-71175600-b638-11ea-8cf0-49a4f0ddc13d.png">

_No segundo é o que eu estou tentando gerar (DM)._
<img width="706" alt="Screen Shot 2020-06-24 at 16 33 09" src="https://user-images.githubusercontent.com/7966620/85619283-72e11980-b638-11ea-9b65-cb73a29cf799.png">

Não tenho acesso ao código do sistema legado então nem tenho como me guiar de uma melhor forma.

**Comment by fredroo** [comment]
@Rctnet consegue ajudar? olha o outro projeto enquanto isso @marcellribeiro

**Comment by Rctnet** [comment]
@marcellribeiro , dei uma conferida, e nem no código de barras, nem na linha digitável aparece a especie do documento, então pode ser que tenha um outro problema com a sua remessa, que esteja invalidando o envio, normalmente os sistemas do banco indicam quando o arquivo não foi processado e o motivo, e no fim o pessoal do banco tem acesso ao arquivo e pode te ajudar mais

**Comment by fredroo** [comment]
@marcellribeiro leia mais sobre os arquivos de remessa https://github.com/QuilhaSoft/OpenCnabPHP

**Comment by marcellribeiro** [comment]
Ok. Vou revisar o arquivo de remessa e tentar entrar em contato com o pessoal do banco. Muito obrigado @fredroo e @Rctnet pela contribuição e parabéns pelo excelente trabalho!
