### ISSUE TITLE
Layout HTML homologado pelo BB!

### ISSUE THREAD

**Issue by lukBarros** [openboleto/openboleto#152]
Amigos implementamos no @simplescontrole o boleto BB com openboleto e submetemos a análise do BB e a resposta fo:

Leiaute de Imagem do boleto “BOL01 (1).pdf“: dentro dos padrões, portanto VALIDADO / HOMOLOGADO.

**Comment by fredroo** [comment]
@lukBarros como já está no readme como homologado vou fechar sua issue

**Comment by fredroo** [comment]
@Rctnet acho que ele está falando do PDF que estava em beta

**Comment by lukBarros** [comment]
Isso PDF
