### ISSUE TITLE
Desconto até o vencimento

### ISSUE THREAD

**Issue by marcellribeiro** [openboleto/openboleto#156]
Alguém consegue me dar uma luz pra entender como dar desconto até a data de vencimento? 
Caso seja pago após o vencimento o valor a ser cobrado e o "valor cheio". 

Pelo que eu entendi se eu usar o "descontosAbatimentos" o desconto vai ser dado mesmo que seja pago após o vencimento né?

**Comment by Rctnet** [comment]
Ola @marcellribeiro , na verdade essas questões de descontos, juros e multas, no boleto vc só coloca na area da mensagem do boleto, lá vc pode escrever o que quiser, mas o que faz os valores serem realmente considerados dentro dos sistemas dos bancos, são os dados enviados na remessa, para entender melhor como funcionar acesse https://github.com/QuilhaSoft/OpenCnabPHP

**Comment by marcellribeiro** [comment]
Verdade, eu acabei me confundindo aqui. Muito obrigado @Rctnet =)
