### ISSUE TITLE
Carnê Com OpenBoleto 

### ISSUE THREAD

**Issue by alfasyssistemas** [openboleto/openboleto#162]
Alguém tem um exemplo funcional de como gerar carnê,

Aqui tem umas respostas, mas as soluções não foram colocadas de forma mais claras se alguém puder ajudar agradeço muito

Obrigado.

**Comment by fredroo** [comment]
@alfasyssistemas tem o projeto na descrição, que gera o boleto em carnê [JasperPHP](https://github.com/openboleto/JasperPHP-OpenBoleto)
