### ISSUE TITLE
Boleto Unicred - Divergências no processo de homologação

### ISSUE THREAD

**Issue by FelipeMichelon** [openboleto/openboleto#163]
No processo de homologação do boleto da Unicred foram levantadas algumas divergências:
1º - Número do banco divergente. O número da Unicred é 136-8.
2º - Título do campo cedente incompatível. O correto é "Beneficiário".
3º - Preenchimento incompleto dos dados do cooperado.
4º - Inconsistência no título “Agência/Código cedente”. O correto é “Agência/Código Beneficiário”.
5º - Inconsistência no título de “Sacado”. O correto é "Pagador".

Não encontrei nenhuma outra issue relacionada ao processo de homolgação do boleto da Unicred. Por isso, abri essa para destacar os pontos a serem corrigidos e para avisar que estarei trabalhando nessas correções nos próximos dias e farei um pull request assim que estiver pronto.

**Comment by Rctnet** [comment]
Olá , está usando o layout html integrado ao openboleto?
recomendo usar https://github.com/QuilhaSoft/JasperPHP-OpenBoleto
que gera o boleto direto em PDF e o mesmo layout já foi homologado em diversos bancos
mesmo assim acredito que o item 1 tenha que ser ajustado

**Comment by FelipeMichelon** [comment]
> Olá , está usando o layout html integrado ao openboleto? recomendo usar https://github.com/QuilhaSoft/JasperPHP-OpenBoleto que gera o boleto direto em PDF e o mesmo layout já foi homologado em diversos bancos mesmo assim acredito que o item 1 tenha que ser ajustado

**Comment by FelipeMichelon** [comment]
Rogerio, sim, pensei em utilizar o JasperPHP, mas me pareceu que ia aumentar muito a complexidade para o que eu preciso, visto que eu teria que estudar como funciona e implementar ele tmabém. Neste caso estou usando o layout intergrado do openboleto mesmo e parece que vai atender bem a necessidade.

Sobre as divergências que destaquei anteriormente, percebi em um teste hoje que o problema acontece na versão v1.0, mas que na versão dev-master todos os campos parecem já ter sido corrigidos.

Vou estar gerando o boleto com a dev-master mesmo e submetendo para homologação. Assim que tiver um retorno da análise do boleto eu comento aqui para acompanhamento.

**Comment by FelipeMichelon** [comment]
A Unicred permite registrar o boleto por API, porém a verificação da baixa do boleto não se dá por API nem por webhook. Desta forma, o processo de geração de boletos com a Unicred foi abortado, pois o cliente teria que fazer a baixa manualmente de cada um dos boletos, tornando o processo inviável.
