### ISSUE TITLE
Mover pasta docs para outro repositório (-27MB)

### ISSUE THREAD

**Issue by vitorccs** [openboleto/openboleto#166]
Recomendo mover a pasta `/docs` para um novo repositório (ex: `openboleto/homologacao`), liberando 28MB de espaço.

Este repositório deveria focar apenas no código-fonte (o que totaliza apenas 500KB).

===

Quem trabalha com outras linguagens como Node.js sabe como a longo prazo a pasta das dependências (bibliotecas) vai ficando cada vez mais volumosa. Quando trabalhamos com funções Serverless, Containers etc de grandes fornecedores como AWS estamos também sujeitos a um tamanho de projeto. 

Creio ser uma ação super simples de fazer, 0 impactos ou alterações no código-fonte e altamente benéfica (ex: https://github.com/openboleto/openboleto/issues/114)

Eu particularmente poderia fazer a PR para remover essa pasta, mas ainda assim, precisaria que alguém da equipe da openboleto criasse o novo repositório, e mencionasse o link dele no README deste projeto. Que tal?

**Comment by fredroo** [comment]
@Rctnet achei uma boa ideia, qual sua opinião?

**Comment by Rctnet** [comment]
Eu acho correto, no meu projeto opencnabphp já é assim, ficou assim https://github.com/QuilhaSoft/OpenCnabPHP-Docs

**Comment by vitorccs** [comment]
@fredroo e @Rctnet criei uma PR para remover a pasta `docs` https://github.com/openboleto/openboleto/pull/171

Conforme o @Rctnet aplicou em outro projeto, estes arquivos não seriam perdidos, mas movidos para um novo repositório - porém, essa 2a etapa precisaria ser feito por alguém da equipe.

===

Segue mais uma evidência de como 27MB em arquivos estáticos podem comprometer alguns projetos:

Abaixo, a documentação AWS Lambda (executar códigos PHP em ambiente serverless) 

![screenshot-docs aws amazon com-2022 03 29-11_27_38](https://user-images.githubusercontent.com/9891961/160634596-f3f1e3ce-576b-4a4c-8efb-0037b78dc5e6.png)

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

Eu poderia ter criado um script em meu projeto para que a cada deploy, fosse até este repositório e apagasse essa pasta `docs`, mas achei melhor contribuir com a comunidade aqui.

**Comment by Rctnet** [comment]
Olá, @fredroo, poderia criar o repositório para guardar os docs, para nós, eu não tenho permissão para isso.

**Comment by fredroo** [comment]
@Rctnet criei o repo e te coloquei como admin, pode mudar conforme o amigo indicou openboleto/docs

**Comment by Rctnet** [comment]
Olá @vitorccs , repositório criado, agora é só colocar as docs nele e manda uma PR

**Comment by vitorccs** [comment]
@fredroo e @Rctnet show! agradeço a parceria

**Comment by fredroo** [comment]
@vitorccs nós que agradecemos pela ajuda. ficamos a disposição em novas melhorias que você tiver no futuro.
