### ISSUE TITLE
OpenBoleto x Dompdf 

### ISSUE THREAD

**Issue by Walfridocesar** [openboleto/openboleto#182]
Estou usando o Dompdf para imprimir os boletos, mas ele não carrega a formatação correta do CSS, tem alguma solução?

    $dompdf = new Dompdf(['enable_remote' => true ]);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->load_html($boleto->getOutput(), 'UTF-8');
    $dompdf->render();
    // Enviando o PDF para o browser
    header('Content-type: text/html; charset=UTF-8');
    $dompdf->stream("dompdf_out.pdf", array("Attachment" => false));

**Comment by nicolahsss** [comment]
O Jasper não atende sua solicitação?

**Comment by nichdemos** [comment]
Oi @nicolahsss!

> O Jasper não atende sua solicitação?

que boa ideia!
