### ISSUE TITLE
posso divulgar esse projeto para meus amigos desenvolvedores?

### ISSUE THREAD

**Issue by nichdemos** [openboleto/openboleto#186]
Oi equipe @openboleto, como estão?

eu tenho permissão para divulgar esse projeto para meus amigos desenvolvedores? Existe algum direito de imagem ou marca registrada neste projeto de código aberto que restrinja a divulgação e promoção deste projeto?

**Comment by fredroo** [comment]
@nichdemos pode divulgar sim, tem as logos dos bancos, mas como é para o uso nos boletos deles, acredito que não tenha problema.
