### ISSUE TITLE
Modelo de Integração de QR Code

### ISSUE THREAD

**Issue by fredroo** [openboleto/openboleto#200]
Alguém por favor que já tenha integrado algum QR Code ao boleto, por favor enviar um exemplo do que precisa ser feito em um banco seja ele qual for, também é bom escrever como seria para implementar nos outros banco, se tiver ideia de como seria feito. Enviar PR por favor, obrigado desde já.

**Comment by fredroo** [comment]
@lucasnpinheiro acha que consegue ajudar com isso? qual banco você implementou foi BB?

**Comment by gersonfs** [comment]
Tenho esses 2 abaixo. O primeiro é do Sicredi que fizemos para um cliente. O segundo é o que vem da API Da Caixa que usamos para registrar online.

![image](https://github.com/openboleto/openboleto/assets/293154/ebf82840-fda2-4d6b-8ee4-4c78863db6dc)


Boleto Caixa:
![image](https://github.com/openboleto/openboleto/assets/293154/6a665068-bb76-4ed4-b2f3-391ccab64e55)

**Comment by fredroo** [comment]
@gersonfs mas eu digo um exemplo do que a pessoa que quer implementar deve fazer para integrar, deve procurar o banco? Os bancos tem documentação?

**Comment by gersonfs** [comment]
Ah entendi mal, em ambos usei API do banco.
No Sicredi tem a documentação que é enviada só após o cliente contratar esse produto. É enviado para o e-mail do cliente.
Já na Caixa a documentação é pública: https://www.caixa.gov.br/Downloads/cobranca-caixa/WEBSERVICE-XML-COBRANCA-BANCARIA.pdf
Aí basta só o cliente contratar esse produto também.

**Comment by fredroo** [comment]
@gersonfs então no caso tem uma cobrança? outro ponto, se vencer, o pix não vale mais?

**Comment by gersonfs** [comment]
Não sei te dizer se o boleto com pix tem valor diferente do sem. 
A API do Sicredi tu pode especificar quantos dias após o vencimento ele ainda pode ser pago com PIX, daí é calculado multa e juros igual ao boleto.
Da caixa não tem parâmetro para tal, eu imagino que deve ser o mesmo parâmetro que é usado para pagar o boleto normal.

**Comment by gersonfs** [comment]
Hoje estamos tendo problema no Sicredi ao mudar a data de vencimento, o QRCode não está mudando... Ele deveria atualizar também.

**Comment by fredroo** [comment]
@gersonfs mas esse que você usa foi tudo implementado por sua equipe certo? Quis dizer se tem cobrança de taxa para a empresa se ela receber no pix já que o banco deixou de receber pelo boleto? Você consegue escrever no readme algo explicando o básico para as pessoas não ficarem perdidas, pois se não de nada adiantou implementar o pix

**Comment by gersonfs** [comment]
Sim, foi implementado por nós, mas esses detalhes comerciais entre meu cliente e o banco eu não tenho acesso. Eu vou ver com ele uma hora dessas qual é a proposta que o banco fez.
