### ISSUE TITLE
Erro na geração do Boleto Bradesco (linha digitável com 48 dígitos)

### ISSUE THREAD

**Issue by vitorccs** [openboleto/openboleto#204]
### Descrição
Pela primeira vez em milhares de boletos emitidos, notei que a biblioteca gerou um boleto Bradesco com linha digitável incorreta. Ficou nítido de identificar pois ele foi gerado com 48 dígitos ao invés de 47. 

### Impacto:
Não é possível realizar o pagamento do boleto pela linha digitável.

### Como reproduzir
+ Baixar o repositório diretamente do Github (última versão) 
+ Criar o arquivo index.php na raíz
+ Depois apenas executei `php index.php` no terminal, e ele mostra o erro
+ Se "dataVencimento" for igual ou após "2025-02-22", ocorre o erro (48 dígitos)

Obs:
+ Mesmo que colocando a data com muitos meses ou anos a frente, o erro segue - é como se o cálculo "quebrasse" após "2025-02-22"
+ Os dados da carteira, do sacado e cedente indeferem: na verdade, foi pelo meus dados reais, que pude primeiro notar o problema

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

require __DIR__.'/vendor/autoload.php';

$b = new \OpenBoleto\Banco\Bradesco([
    'cip' => 865,
    'carteira' => 26,
    'agencia' => '0001',
    'agenciaDv' => 9,
    'conta' => '1234567',
    'contaDv' => 4,
    'especieDoc' => "Outro",
    'numeroDocumento' => 1891967,
    'dataDocumento' => new DateTime('2024-03-01'),
    'dataProcessamento' => new DateTime('2024-03-01'),
    'dataVencimento' => new DateTime('2025-02-22'),
    'valor' => 30,
    'sequencial' => 390024,
    'sacado' => new \OpenBoleto\Agente(
        'João Silva Souza',
        '256.420.826-63',
        'Rua Teste, 123',
        '49320-971',
        'Cidade',
        'SE'
    ),
    'cedente' => new \OpenBoleto\Agente(
        'DADOS EMPRESA',
        '57.270.533/0001-00',
        'Rua Teste, 123',
        '49320-971',
        'Cidade',
        'SE'
    ),
    'descricaoDemonstrativo' => 'demonstrativo',
    'instrucoes' => 'instrucoes',
]);

echo "\n";
echo $b->getLinhaDigitavel();

echo "\n";
echo strlen(preg_replace("/[^0-9]/", '', $b->getLinhaDigitavel()));

echo "\n";
```

**Comment by vitorccs** [comment]
Confirmado que o problema tem relação com a "Data de Vencimento" do Boleto, mais exatamente no valor do "Fator de Vencimento":
+ Ele só pode ter 4 dígitos
+ No dia 21/02/205  ele alcança o valor máximo (9999)
+ Quando ele chega 22/02/2025 ele alcança o 5o dígito (10000)

O banco Bradesco orienta nesse caso a reiniciar a contagem para 1000 a partir de 22/02/2025

Página 34 do link abaixo:
https://banco.bradesco/assets/pessoajuridica/pdf/4008-524-0121-layout-cobranca-versao-portugues.pdf
![image](https://github.com/openboleto/openboleto/assets/9891961/a664caa2-0cfb-47da-bba0-d73b6dea0b1e)

**Comment by fredroo** [comment]
@vitorccs https://github.com/openboleto/openboleto/pull/207

**Comment by vitorccs** [comment]
Obrigado @fredroo e @Joao-Bittencourt !!

Testei em minha carteira do banco Bradesco em produção e funcionou perfeito!! 🎉  👏🏻
