### ISSUE TITLE
Problemas ao validar boleto pelo bradesco

### ISSUE THREAD

**Issue by alphabraga** [openboleto/openboleto#22]
Olá,

Primeiro queria agradecer o incrível trabalho de todos os envolvidos nesse projeto. Ficou melhor e mais fácil trabalhar com boletos com o projeto de vocês.

Estou tento problemas com o boleto do Bradesco. No momento de homologar o boleto pelo banco (no  caso Bradesco) o mesmo fez a seguinte consideração:

"Campo nosso número: deve ser composto por carteira, onze caracteres e dígito  EX.:  ( 09/ XXXXXXXXX11-9 )"

O método que deveria gerar o nosso número apenas retorna o sequencial:
https://github.com/kriansa/openboleto/blob/master/src/OpenBoleto/Banco/Bradesco.php#L86

Esse método não deveria gerar o nosso número como descrito acima? Eu fiz algumas modificações no código, estou aguardando o banco homologar. Assim que isso acontecer faço um pull request.

**Comment by jhonnymakis** [comment]
Boa tarde!
@kriansa eu inclui a carteira 26 para o Bradesco, fiz também a geração do digito de auto conferência, passei para a view do boleto a visualização correta do nosso numero no formato XX/00000000000-0 ou XX/00000000000-P (carteira/nosso_número-digito_de_auto_conferencia)

**Comment by jhonnymakis** [comment]
Para passar o valor correto para a view basta alterar a função \Banco\Bradesco.php
<pre>
    public function getViewVars()
    {
        return array(
            'cip' => self::zeroFill($this->getCip(), 3),
            'mostra_cip' => true,
            'nosso_numero' =>
                str_pad( $this->getCarteira(), 2, 0, STR_PAD_LEFT ) . '/' .
                str_pad( $this->getNossoNumero(), 11, 0, STR_PAD_LEFT ) . '-' .
                $this->digitoAutoConferencia
        );
    }
</pre>

**Comment by lecas93** [comment]
Muito obrigado pela solução previa @jhonnymakis  espero que o projeto seja atualizado pois realmente ele é muito bom e organizado, estou usando ele com cakephp 3

**Comment by andreisena** [comment]
Ao tentar homologar também tive esse problema. Utilizei a solução do @jhonnymakis e o digito verificador estava sendo gerado incorretamente. Ao gerar o módulo 11, é necessário passar também o número da carteira.
`$modulo11 = $this->modulo11( str_pad( $this->getCarteira(), 2, 0, STR_PAD_LEFT ) . str_pad( $sequencial, 11, 0, STR_PAD_LEFT ), 7 );`
