### ISSUE TITLE
[Boletos ITAU] - Código de barra inválido

### ISSUE THREAD

**Issue by thekaduu** [openboleto/openboleto#24]
Boletos para o banco itau em qualquer carteira não passa no internet Banking, dá "Código de Barra INVÁLIDO", como exemplo pode-se testar com o Sample itau.php

**Comment by paulovitin** [comment]
Os dados do sample realmente não funciona...

Teste a seguinte configuração:
```php
use OpenBoleto\Banco\Itau;
use OpenBoleto\Agente;
 
$sacado = new Agente('Fernando Maia', '023.434.234-34', 'ABC 302 Bloco N', '72000-000', 'Brasília', 'DF');
$cedente = new Agente('Empresa de cosméticos LTDA', '02.123.123/0001-11', 'CLS 403 Lj 23', '71000-000', 'Brasília', 'DF');
 
$boleto = newItau(array(
    // Parâmetros obrigatórios
    'dataVencimento' => new DateTime('2015-05-29'),
    'valor' => 1490,
    'sequencial' => 105, // Para gerar o nosso número
    'sacado' => $sacado,
    'cedente' => $cedente,
    'agencia' => 4536, // Até 4 dígitos
    'carteira' => 175,
    'conta' => 09053,
    'contaDv' => 5
));
 
echo $boleto->getOutput();
```

**Comment by Fabyo** [comment]
Sei que é antigo, mas vou deixar uma dica caso alguem mais tenha problemas, como eu tive esses dias, a linha digitavel do itau estava dando erro, dai descobri que era um espaço em branco na agencia.

**Comment by Fabyo** [comment]
Criei um sistema que o cliente cadastra suas contas, dai o boleto é gerado apartir dos dados do banco, e estava dando erro no codigo digitavel, dai fui ver o cliente tinha cadastrado um espaço em branco na agencia, dai usei trim antes de salvar e resolveu

**Comment by aCidcOde** [comment]
Eu ainda tenho este problema, estou investigando para resolver.
Já verifiquei o que o amigo acima falou  e foi isso.

**Comment by aCidcOde** [comment]
Ainda continuo com o mesmo problema, alguem achou uma solução?
