### ISSUE TITLE
Fork do openboleto em JS

### ISSUE THREAD

**Issue by kriansa** [openboleto/openboleto#25]
Caros,

Peço desculpas por não estar tão ativo atualmente no projeto, mas a desculpa é na verdade uma boa notícia: estou migrando o OpenBoleto para JS, com o intuito de não somente funcionar diretamente do browser (ou do nodejs) mas também fazer integrações com todas as linguagens de programação possíveis.

Outra novidade é que já iniciei o trabalho nos arquivos de retorno, e já tenho 5 bancos homologados.

Ainda não tenho um nome definido para esse novo projeto, mas a idéia é que como ele também terá integração com o PHP, eu descontinue o OpenBoleto em prol deste novo.

Assim que tiver alguma versão funcional, estarei liberando o projeto no github e linkando aqui.

Estou aberto à sugestões.
Abraços!

**Comment by HwapX** [comment]
Alguma noticia sobre o Fork?

**Comment by paulovitin** [comment]
?

**Comment by kriansa** [comment]
Sorry about that ppl!!

Desde meu último update não tive tempo de atualizar o projeto, estive em processo de mudança de emprego e de estado, e tudo isso me deixou meio por fora do OSS.

Estou retornando hoje e pretendo postar o projeto nessa semana, mas ainda faltam muitos ajustes na arquitetura, portanto vou deixar ele readonly por enquanto.

Quanto ao openboleto vou aceitar os pull requests atuais para não deixar que o projeto se desfaça.

Me dêem até quinta feira para ajustar isso. Aos que estiverem mais interessados, podem entrar em contato comigo pelo daniel@garajau.com.br

Obrigado pela paciência ;)

**Comment by jonataswalker** [comment]
@kriansa e demais interessados!

Preciso do boleto em JavaScript e fiz uma conversão deste projeto e está apenas para o Banco do Brasil (minha prioridade) mas não será difícil fazer uma abstração maior e incluir outros bancos.

Muito obrigado pelo código organizado e comentado.

https://github.com/jonataswalker/boleto-bb

**Comment by jonataswalker** [comment]
Ah ... faltou dizer que está totalmente sem testes e muita coisa precisa ser corrigido/adaptado/melhorado.
