### ISSUE TITLE
Digito verificador nosso número da caixa

### ISSUE THREAD

**Issue by rodrigotavio91** [openboleto/openboleto#26]
Olá, estava usando o seu modulo em uma aplicação, e gostei muito do formato. Muito simples de aplicar. Já trabalhei com o código puro do boletos php e sei como falta organização. 
Mas estava observando a geração do digito do nosso numero, e estava sempre vindo 8. Fiz o teste com os mesmos valores com o codigo original do boletos php e retornava 1. E também sempre varia. Mas o do seu módulo esta mantendo sempre 8.
Fui procurar a solução, e vi que na função geraNossoNumero() da Caixa esta passando para a função modulo11() apenas o numero baseado na carteira (24 ou 14), enquanto no código original é  passado este  mesmo numero mais o sequencial fornecido no código. Por exemplo:
Se o meu sequencial é 222 e minha carteira é SR, o parametro da função modulo11() deveria ser 24.zeroFill(222, 15), que ai retornaria o digito correto, e não 8 como esta retornando sempre. 
Acredito que não seja engano meu, pois se vc passar sempre 24 para o modulo11(), o retorno nunca vai variar.
Da uma conferida ai e parabéns pelo ótimo trabalho.
Abraço

**Comment by kriansa** [comment]
@zardo Descobriu o que poderia ser isso?
