### ISSUE TITLE
OpenBoleto & Novas regras BACEN

### ISSUE THREAD

**Issue by kriansa** [openboleto/openboleto#53]
## Novas regras do Bacen

No início do ano passado, o **Febraban** emitiu um comunicado interno aos bancos sobre o fim das cobranças sem registro.

À partir de janeiro de 2017, todas as carteiras sem registro deverão ser migradas para **com registro**. Os boletos que ainda forem emitidos sem registro só poderão ser recebidos pelo próprio banco emissor.

Isso está gerando trabalho para muita gente que depende de boletos como forma de pagamento. Com isso, quero criar aqui espaço para que sejam criadas as devidas alterações para que a library seja compatível com essas alterações, que são:
- Geração de arquivo de remessa
- Validação de carteiras registradas
- Homologação junto aos bancos

Fontes: 
- http://www.projetoacbr.com.br/forum/topic/21722-fim-de-boletos-sem-registro
- https://www.docdroid.net/KhRvicP/comunicado-fb-015-2015.doc.html
## E o OpenBoleto?

Claramente não é tarefa simples. O OpenBoleto por minha culpa está um pouco largado (muito por falta de tempo). Estou com um projeto em paralelo em JS, mas ainda não está maduro o suficiente para um release. Com isso, pretendo voltar com a atividade no OpenBoleto. 

Entretanto, como já estou há algum tempo fora do PHP, não tenho mais a mesma expertise de antes, estou mais vulnerável a cometer erros. Vou me focar mais na gerência deste projeto, em aspectos como:
- Qualidade
- Documentação
- Criação de diretrizes para contribuidores
- etc

O meu objetivo é aumentar a qualidade do projeto, e a facilidade/boa experiência de contribuir para o mesmo. 

Então gostaria de saber o que acham/esperam desta decisão, se existe algo onde eu possa mudar, ou qualquer outro feedback!

Obrigado :+1:

**Comment by fredroo** [comment]
Daniel já existe um projeto muito bom para trabalhar com os arquivos de remessa e ler o arquivo de retorno, acho que seria mais interessante a gente contribuir lá e deixar os projetos como irmãos.

Segue o link:
https://github.com/andersondanilo/CnabPHP

**Comment by fredroo** [comment]
concordo, eu já tenho contato com o responsável, vou falar com ele para as bibliotecas serem parceiras, sendo assim evitando criar algo que já existe e com boa qualidade das duas.

**Comment by Fabyo** [comment]
Eu acho valido ter mais opções de projetos em vez de um só, deixando esse projeto aqui com esse recurso é muito melhor, no meu caso num projeto estou usando openboleto, cnab do danilo mas como ele nao tem a opçao para o bradesco ou crio ou tenho que usar outra lib, acaba ficando muito ruim manter um projeto assim, é muito melhor se tivesse uma lib mais completa

**Comment by fredroo** [comment]
é mais vantajoso contribuirmos lá do que começar a reinventar a roda

**Comment by Fabyo** [comment]
Isso nao é reinventar a roda, é diversidade e opções, é muito mais vantajoso o openboleto ser mais completo do que eu ter que usar 4 pedaços de projetos para ter um resultado em comum

**Comment by kriansa** [comment]
@fredroo @Fabyo Não precisa nem um nem outro.

Pode-se criar uma abstração que utiliza as duas bibliotecas por baixo, não faltam patterns pra isso. Resolvemos o problema de não precisar conhecer as regras de negócio de duas libraries diferentes e ter que reinventar a roda.
