### ISSUE TITLE
Integrar com H2P para geração de PDF

### ISSUE THREAD

**Issue by kriansa** [openboleto/openboleto#55]
Já é uma funcionalidade muito pedida.

**Comment by Fabyo** [comment]
Bom Dia
estou tentando usar o H2P enquanto nao tiver disponivel oficialmente no openboleto, mas esta dando erro de permissao, estou usando windows 7

baixei o phantom e copiei certinho para as pastas certa
ele chega a gerar o boleto na pasta de destino mas vazio

o erro é : ErrorException [ Warning ]: shell_exec(): Unable to execute 

pode dar uma dica?

obrigado

**Comment by Fabyo** [comment]
Só mais um detalhe usei TempFile e agora nao mostra nenhum erro na tela, porem ainda gera o pdf vazio

**Comment by Rogeriociatecnet** [comment]
Bom tarde Fabyo eu ainda não cheguei nessa parte com o boleto mas uso para conversação de HTML em PDF e nao tenho nenhuma dificuldade 
https://github.com/tecnickcom/TCPDF
http://www.tcpdf.org/examples.php

**Comment by Fabyo** [comment]
Obrigado Rogerio!

eu ja uso uma lib muito boa:
https://github.com/KnpLabs/snappy
http://wkhtmltopdf.org/

só que o Daniel Garajau(kriansa) recomendou usar o H2P, achei que seria mais rapido e melhor gerar com ela, mas nao funciona, essa H2P esta desatualizada a 3 anos acho que mudou alguma coisa porque nem os exemplos dela funciona

**Comment by Rogeriociatecnet** [comment]
Obrigado pela resposta Fabyo mas eu estive olhando essa lib knplabs e vi que ela depende de binários externos ao PHP. Ela é realmente  tão boa assim? Eu uso a tcpdf por ser em PHP puro, não testei ela com páginas completas mas uso em conjunto com um editor de testo online para geração de documentos personalizados e tem sido fiel nos meus testes.

**Comment by Fabyo** [comment]
Oi Rogerio ela é realmente muito boa, e o fato de ter uma dependencia nao prejudica em nada, tem versoes para windows e linux, eu ja usei muito o tcpdf mas o  wkhtmltopdf gera um pdf mais fiel e com mais recursos, pensei em usar o H2P por ele usar o phantomJS que roda em nodeJS e é possivel fazer uma conversao para pdf só com javascript e eu achei que ela seria mais rapida, mas ainda nao consegui fazer funcionar

**Comment by Rogeriociatecnet** [comment]
Legal, bom saber que tem algum recuso caso precise.

**Comment by fredroo** [comment]
atualmente estou usando este projeto http://www.html2pdf.it

**Comment by Rogeriociatecnet** [comment]
Adicionei hoje no meu fork e  abri uma pull request com as alterações para codigo de barras de imagem unica e geração de pdf com a classe dompdf/dompdf. em minha defesa digo que com o dompdf mantemos o projeto em puro php garantindo maior desempenho. o contra é que o dompdf funciona como um navegado mal comportado no que diz respeito ao css nos obrigando a fazer algumas aberrações no layout para que tudo funcione.

**Comment by realcofre** [comment]
Olá @kriansa você tem um exemplo de integração do OpenBoleto com o H2P?

**Comment by Rctnet** [comment]
Dá uma olhada em quilhasoft\jasperPHP-openboleto
