### ISSUE TITLE
Carteira é sobrescrita no boleto itau

### ISSUE THREAD

**Issue by Rctnet** [openboleto/openboleto#59]
o elemento carteira é sobrescrito com undefined na linha 122 do arquivo BoletoAbstract.php
pelo metodo getViewVars(),somente para boleto Itau, alguém sabe como resolver?

**Comment by Rogeriociatecnet** [comment]
Achei e fiz uma alteração em Banco\Itau.php removendo a classe getViewVars(); ainda nao fiz a validação dessa informação mas vi que tem em outros boletos, quando testar junto ao banco posto aqui novamente

**Comment by kriansa** [comment]
Pode mostrar um exemplo de como você está fazendo?

**Comment by Rogeriociatecnet** [comment]
Primeiro desculpe minha falta de atenção. não foi removida a classe, foi o método getViewVars(), para mostrar como fiz alterei atualizei o arquivo https://github.com/Rogeriociatecnet/openboleto/commit/d36c027b7d01b5e1760209d3ccc5dc61a7c0e223 no meu fork.
