### ISSUE TITLE
Nosso número Santander

### ISSUE THREAD

**Issue by RenanPalmeira** [openboleto/openboleto#63]
Eu tive problemas com o boleto Santander, a homologação sempre apontava erro no Nosso Número da linha digital, o Nosso Número segunda essa documentação & o suporte do banco, tem que passar pelo módulo11 :
- Minha alteração - https://github.com/Forleven/openboleto/commit/08b7431e9f053e556f5f40a85933c0e461360e45
- Documentação - página 13 - https://github.com/eduardocereto/pyboleto/blob/master/specs/Santander/Layout%20de%20Cobran%C3%A7a%20-%20C%C3%B3digo%20de%20Barras%20Santander%20Setembro%202012%20v%202%203.pdf

**Comment by ricardofontanelli** [comment]
@RenanPalmeira , vc chegou a abrir PR para esta alteração? Se sim, me passa o número, eu tava parado nesse problema do Santander e a sua alteração funciona perfeito.

**Comment by RenanPalmeira** [comment]
Abri sim, segue o PR, https://github.com/kriansa/openboleto/pull/60
