### ISSUE TITLE
Adicionar Carteira 157 do ITAU

### ISSUE THREAD

**Issue by andersoncsales** [openboleto/openboleto#65]
Incluir a carteira 157 do itau.
openboleto/src/openboleto/banco/itau.php 

Array Carteiras, adicionar 157.

**Comment by wemersonjanuario** [comment]
Gostaria de emitir boletos também com essa carteira.

**Comment by andersoncsales** [comment]
Eu corrigi no meu código e funcionou perfeitamente! mas ainda não atualizaram a carteira no código fonte.
