### ISSUE TITLE
Banco SICOOB

### ISSUE THREAD

**Issue by amrigo** [openboleto/openboleto#70]
Boa noite,

Gostaria de implementar boleto para o Banco SICOOB, qual seria o caminho ?

**Comment by wemersonjanuario** [comment]
tem um fork para sicoob do @vfeitoza aguardando merge. Estou usando ele e está funcionando perfeitamente e homologado.

Faz require do branch dele
"kriansa/openboleto": "dev-sicoob",

e add o repositório

"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/vfeitoza/openboleto"
    }
]

espero ter ajudado.

**Comment by amrigo** [comment]
Perfeito Wemerson!
Baixei a classe no diretório OpenBoleto/Banco configurei e gerou boleto direitinho!
Obrigado pela ajuda!
