### ISSUE TITLE
Boleto Caixa Carteira Registrada

### ISSUE THREAD

**Issue by lucioabrantes** [openboleto/openboleto#76]
Boa tarde,

Preciso fazer as alterações para aceitar a carteira CR na caixa, e também inserir o CPF/CNPJ do sacado na ficha de compensação, o que acha, alterar direto, ou criar um novo partial para a ficha de compensação com CPF/CNPJ do sacado?

**Comment by ronaldsena** [comment]
A biblioteca OPENBOLETO gerar boletos registrados da CEF e também cria o arquivo REMESA (.rem) o qual tem que ser enviado para o banco ??????

**Comment by Rctnet** [comment]
Não, na verdade existe um problema em gerar o arquivo na emissão do boleto, o envio dá remessa normalmente é feito uma vez ao dia, então a biblioteca openboleto não se interessou em seguir esse caminho, eu recomendo a biblioteca quilhasoft/opencnabphp para gerar o arquivo.

**Comment by ronaldsena** [comment]
Rctnet obrigado pela resposta porem surgiu algumas duvidas.

No caso a biblioteca openboleto gerar os boletos já no padrão registrado, porem não gerar o arquivo remessa (.rem) ?

Desta forma eu posso utilizar a openboleto para gerar o boletos e um outra biblioteca para apenas para gerar o arquivo (.rem) ?

**Comment by Rctnet** [comment]
Sim e sim.

**Comment by lucioabrantes** [comment]
Na verdade precisa de duas pequenas alterações, exibir carteira CR, e o CPF/CNPJ na parte de baixo, vou fazer isso e mandar
