### ISSUE TITLE
Projeto foi abandonado?

### ISSUE THREAD

**Issue by lukBarros** [openboleto/openboleto#80]

**Comment by eerison** [comment]
Acredito que não, por que estou usando!
mas por que acha isso?

**Comment by fredroo** [comment]
o dono do projeto não da atenção, vou fazer um fork e passamos a usar o meu

**Comment by fredroo** [comment]
já tentei contato via skype

**Comment by Rctnet** [comment]
Bem eu não acredito mais no boleto com layout em HTML e a conversão para PDF é penosa, por isso adaptei o meu projeto para gerar direto PDF, isso quer dizer que ainda uso a base desse projeto para manter o meu, não gostaria de velo encerrado ou abandonado.

**Comment by eerison** [comment]
pois é :( ele não ta dando sinal de vida :(

**Comment by albandes** [comment]
Eu fiz uma versão em pdf q funciona há muitos anos, se quiserem posso enviar e/ou ajudar !

Abs


--
Rogério Albandes
IT Coordinator at Instituto Educacional MQ: +55 53 3321-6756
Owner at Pipegrep: +55 53 3025-6043
Mobile: +55 53 8401-4872

**Comment by Rctnet** [comment]
Obrigado @albandes, mas meu projeto já esta bem azeitado e esta disponível em https://github.com/QuilhaSoft/JasperPHP-openboleto, esse projeto une o openboleto 
ao JasperPHP, esse ultimo lê um arquivo de layout de relatório editado com JasperSoft-Studio
e gera uma saída pdf, feito inteiramente em PHP sem a necessidade de um servidor java.

**Comment by rafa-acioly** [comment]
@albandes qual o repositório que você esta usando agora?

**Comment by albandes** [comment]
Ola.

Ele não está público, mas a tarde, quando chegar na empresa eu te evio e tu
avalia.

Abs



*Rogério Albandes*

*IT Coordinator at Instituto Educacional MQ: +55 53 3321-6756*
*Owner at Pipegrep: +55 53 3303-0244*
*Helpdezk - Project Leader: helpdez.org <http://helpdez.org/>*
*Mobile: +55 53 8401-4872*


2017-04-03 10:54 GMT-03:00 Rafael Acioly <notifications@github.com>:

**Comment by albandes** [comment]
Bom dia.

Segue em anexo o método.
O array $aBoleto eu "pego" do phpboleto, ou seja, uso os métodos para os
cálculos e na hora de montar gero um .pdf.
Mando mais de 2.000 boletos/mes por e-mail do Sicredi e Santander, sem
problemas, há alguns anos.

Qualquer dúvida, sigo à disposição.

Abs



*Rogério Albandes*

*IT Coordinator at Instituto Educacional MQ: +55 53 3321-6756*
*Owner at Pipegrep: +55 53 3303-0244*
*Helpdezk - Project Leader: helpdez.org <http://helpdez.org/>*
*Mobile: +55 53 8401-4872*


2017-04-03 11:12 GMT-03:00 Rogerio Albandes <rogerio.albandes@gmail.com>:

**Comment by geraldoraimundo** [comment]
Bom dia Albandes

Poderia me enviar sua classe?

**Comment by afranioce** [comment]
Um projeto desse e sem manutenção 👎

**Comment by rafa-acioly** [comment]
@afranioce já existe um `fork` do projeto onde estamos realizando manutenção, veja os comentarios acima.

**Comment by cassone200** [comment]
Projeto aqui continua certo ?

**Comment by rafa-acioly** [comment]
@cassone200 não, leia os comentários acima do seu e verá que o projeto foi movido para outro lugar.

**Comment by kriansa** [comment]
Pessoal, estou promovendo um [call for maintainers](https://github.com/kriansa/openboleto/issues/96) para o projeto. Aqueles que se interessem, dêem uma olhada.

**Comment by guaycuru** [comment]
@rafa-acioly a qual dos 229 forks você se refere?

**Comment by Rctnet** [comment]
Até agora acredito que o que mais concentrou esforços é o fredroo/openboleto, inclusive tenho um fork dele tb

**Comment by Rctnet** [comment]
É com alegria que de hoje em diante o projeto openboleto se torna uma ORG aqui no github sendo mantida por @fredroo , min ( @Rctnet ) e @kriansa.
