### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by kriansa** [openboleto/openboleto#96]
Como é de conhecimento público, este projeto está abandonado.

Por diversos motivos, não consegui dar o merecido esforço para mantê-lo, mesmo sabendo que está sendo utilizado por diversas pessoas.

Por respeito ao projeto e às pessoas que o utilizam, e com o objetivo de centralizar os esforços de manutenção em um repositório apenas, estou abrindo este _call for maintainers_ para que outras pessoas mais ativas possam dar continuidade.

## Tecnicamente, o que muda?

Teremos uma nova [organização](https://github.com/openboleto) no Github, desassociada do meu handle, onde os membros administradores terão a responsabilidade de escrita no repositório.

Os membros iniciais deste time serão escolhidos pelo seu comprometimento com o projeto, como por exemplo, quantidade e qualidade das novas funcionalidades implementadas.

## Como me "candidatar"?

Primeiramente é esperado que você:

* Tenha conhecimento técnico para desenvolver e tomar decisões para o projeto;
* Tenha contribuído através de Pull Requests, comentários, etc;

Me envie um email (_daniel arroba garajau.com.br_) se apresentando, com seu ID no Github e seu Fork para que possamos trocar uma ideia. Não será nada formal, fique tranquilo! 😄 

Espero que com essas ações o projeto possa continuar, independente das pessoas envolvidas. Muito obrigado pela paciência ao longo desses anos.

**Comment by Rctnet** [comment]
Muito bom, enviarei o e-mail ainda hoje.

**Comment by emersonrsoares** [comment]
Bacana, gostaria de contribuir também!

**Comment by gildonei** [comment]
Sou parceiro para darmos continuidade nele tb

**Comment by evaldoprestes** [comment]
Enviei e-mail, também gostaria de contribuir.

**Comment by fredroo** [comment]
O projeto está sendo continuado no https://github.com/fredroo/openboleto
@kriansa tem como redirecionar para o meu fork? estamos atualizando o projeto, quem quiser pode subir melhorias e suporte a novos bancos.
